"""added app_settings table

Revision ID: 0697e8202144
Revises: ad2d7ef3256a
Create Date: 2025-11-23 08:57:34.458926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0697e8202144'
down_revision = 'ad2d7ef3256a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=True),
    sa.Column('org_address', sa.String(length=500), nullable=True),
    sa.Column('org_phone', sa.String(length=50), nullable=True),
    sa.Column('org_email', sa.String(length=120), nullable=True),
    sa.Column('payment_email', sa.String(length=120), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('smtp_host', sa.String(length=200), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=200), nullable=True),
    sa.Column('smtp_pass', sa.String(length=200), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('smtp_use_ssl', sa.Boolean(), nullable=True),
    sa.Column('testing_mode', sa.Boolean(), nullable=True),
    sa.Column('testing_email', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
