"""add employee profile pic location

Revision ID: 20637fd5bc13
Revises: 0697e8202144
Create Date: 2025-11-29 19:34:24.935306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20637fd5bc13'
down_revision = '0697e8202144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
