"""add_partial_unique_index_for_rba_number

Revision ID: 21588d3a5ea7
Revises: 9af9783bfaaa
Create Date: 2025-10-24 18:38:51.247484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21588d3a5ea7'
down_revision = '9af9783bfaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('employees_rba_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('employees_rba_number_key'), ['rba_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
