"""updated user db for lock state and activation key

Revision ID: 2f02a3c1e6f3
Revises: 5ce3d50fcfb3
Create Date: 2025-08-16 11:00:37.370052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f02a3c1e6f3'
down_revision = '5ce3d50fcfb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activation_key', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activation_key')
        batch_op.drop_column('locked')

    # ### end Alembic commands ###
