"""updated activation key to 16 charaters

Revision ID: 3173759a22a7
Revises: e3e365ca537f
Create Date: 2025-11-11 13:40:30.947218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3173759a22a7'
down_revision = 'e3e365ca537f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('activation_key',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('activation_key',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
