"""added nullable total_cost field in the invoice table

Revision ID: 7233d2e02d28
Revises: 92440c0de02b
Create Date: 2025-08-10 15:48:45.190351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7233d2e02d28'
down_revision = '92440c0de02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
