"""db init

Revision ID: 7fd55c95532e
Revises: 
Create Date: 2025-08-07 19:12:07.880167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd55c95532e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activity_name', sa.String(length=51), nullable=False),
    sa.Column('activity_category', sa.String(length=51), nullable=False),
    sa.PrimaryKeyConstraint('activity_name')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=51), nullable=False),
    sa.Column('lastname', sa.String(length=51), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=51), nullable=False),
    sa.Column('parentname', sa.String(length=101), nullable=False),
    sa.Column('parentemail', sa.String(length=120), nullable=False),
    sa.Column('parentcell', sa.String(length=10), nullable=False),
    sa.Column('address1', sa.String(length=120), nullable=False),
    sa.Column('address2', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=51), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zipcode', sa.String(length=6), nullable=False),
    sa.Column('cost_supervision', sa.Float(), nullable=False),
    sa.Column('cost_therapy', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designations',
    sa.Column('designation', sa.String(length=51), nullable=False),
    sa.PrimaryKeyConstraint('designation')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=51), nullable=False),
    sa.Column('lastname', sa.String(length=51), nullable=True),
    sa.Column('position', sa.String(length=51), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('cell', sa.String(length=10), nullable=False),
    sa.Column('address1', sa.String(length=120), nullable=True),
    sa.Column('address2', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=51), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipcode', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['position'], ['designations.designation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=25), nullable=False),
    sa.Column('invoiced_date', sa.Date(), nullable=False),
    sa.Column('payby_date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('intervention_type', sa.String(length=51), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('invoiced', sa.Boolean(), nullable=True),
    sa.Column('invoice_number', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['intervention_type'], ['activities.activity_name'], ),
    sa.ForeignKeyConstraint(['invoice_number'], ['invoices.invoice_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interventions')
    op.drop_table('invoices')
    op.drop_table('employees')
    op.drop_table('designations')
    op.drop_table('clients')
    op.drop_table('activities')
    # ### end Alembic commands ###
