"""converting password_hash field to nullable=true in employee table

Revision ID: 83168b48a8b7
Revises: e138b4c222ce
Create Date: 2025-10-31 23:54:39.215514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83168b48a8b7'
down_revision = 'e138b4c222ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
