"""add intervention_ids to Invoice

Revision ID: 92440c0de02b
Revises: 7fd55c95532e
Create Date: 2025-08-07 21:04:16.058557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92440c0de02b'
down_revision = '7fd55c95532e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervention_ids', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('intervention_ids')

    # ### end Alembic commands ###
