"""set total_cost field in the invoice table to non nullable

Revision ID: a3c7195aff36
Revises: 7233d2e02d28
Create Date: 2025-08-10 15:50:12.302198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c7195aff36'
down_revision = '7233d2e02d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
