"""added secondary email for client

Revision ID: ad2d7ef3256a
Revises: 3173759a22a7
Create Date: 2025-11-22 22:12:11.897587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2d7ef3256a'
down_revision = '3173759a22a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentemail2', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('parentemail2')

    # ### end Alembic commands ###
