"""add invoice_items column to invoices

Revision ID: d2953519d1c0
Revises: 4fe5e5e68042
Create Date: 2025-10-23 09:50:51.780499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2953519d1c0'
down_revision = '4fe5e5e68042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_items', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('invoice_items')

    # ### end Alembic commands ###
