"""add is_active nullable field to client and employee table

Revision ID: d42a871653da
Revises: 373c24b661df
Create Date: 2025-10-25 19:40:15.080537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42a871653da'
down_revision = '373c24b661df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrates', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
